controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /token
    methods: ["POST"]

api_token_refresh:
    path: /token/refresh
    methods: ["POST"]

api_token_invalidate:
    path: /token/invalidate
    methods: ["GET","POST"]